### ISSUE TITLE
consider a master YAML files with all the rules and description

### ISSUE THREAD

**Issue by ccoVeille** [jargonLint/jargonLint#16]
jargonLint could provide something and could dump words in many formats

- a markdown page with metadata such as project category, something like [glosario](https://github.com/carpentries/glosario)
- wordlist
- [contextive](https://github.com/dev-cycles/contextive) format
- vale rules   vale folder in jargonLint (current PR)
- [autocorrect](https://github.com/huacnlee/autocorrect/) format: 
- [teminology](https://github.com/sapegin/textlint-rule-terminology) format

**Comment by ccoVeille** [comment]
this project might help for the master YAML

https://github.com/kislyuk/yq

yq state for jq for YAML

But we might also use a shell script.

@jason3s as some experience with script like this I will have a look at what he did for 

https://github.com/streetsidesoftware/cspell-dicts/tree/main/scripts

**Comment by ccoVeille** [comment]
@alexvonme 
You helped me to understand the Reference file idea I had would be a real pain to maintain. I think I will consider this idea put for now, or at least thibk about generating it from other files, such as the vale rules.

While there is still a need for a master file. It should be generated, not a source.

In addition of smaller files easier to maintain would be better, it would be easier to test

**Comment by ccoVeille** [comment]
Good point, but I'm not worried by this.

We can have a reference YAML per category that will contain everything needed, and the main/too reference YAML is simply a concatenation of all of them.

Here is the structure I'm thinking about

```yaml
- name: GPLv3
   description: GNU Public License v3
   regexp: GPL[- ]?v3
   category: license
   source: link/text

- name: GPL
   description: GNU Public License
   category: license
   source: link/text
```

Then we build: license.yml rule with all terms from the category license

```yaml
# …
swap:
   GPL: GPL
   GPL[- ]?v3: GPLv3
```

   
regexp is optional, when not provided name is used to build
