### ISSUE TITLE
Fix Capitalization avoiders in Licenses.yml

### ISSUE THREAD

**Issue by alexvonme** [jargonLint/jargonLint#64]
The lines below are from the Licenses.yml rule:
```
extends: substitution
ignorecase: true
level: warning
message: Use the suggested license abbreviation '%s' instead of '%s'
action:
  name: replace
swap:
  OFL: OFL
  OFL[ -]?1(?:\.1)?: OFL 1.1
exceptions:
  - OFL-1.1
```
The rule corrects ``ofl`` but avoids ``ofl 1.1``. The same issue can also be seen in other licenses, such as MPL and EPL. 

The issue seems to be that in a complex regex expression where the value for ignorecase is true, the rule doesn't only match the exact phrase on the right side. Instead, the rule allows for ignorecase versions of the right-side expression.

I've seen the problem in VS Code and Vale Studio. Further testing and a possible fix is necessary.
